### ISSUE TITLE
Redesign the Mentor page.

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#83]
We have our mentorpage... In `pages/mentor/[mentorUsername].page.js`

**Comment by dhrumishah** [comment]
I would like revamp it. @anmode

**Comment by Isha988** [comment]
I want to work on this issue.

**Comment by anmode** [comment]
Ig I have assigned both of you issues.. Please complete then I'll assign it!

**Comment by ritik48** [comment]
@anmode please assign this issue to me under GSSoC'23

**Comment by ritik48** [comment]
hey @anmode , every mentor card has different size of contents but a fixed height is applied on all, therefore in some cards 'Book Session' is not seen so we have to scroll the content a bit.

I have thought of  two solution:
#### 1. Making cards take flexible amount of height.
This would make every content of the card visible to user and there will be no scrolling , but there will be some uneven gaps left between the cards
#### Screenshots
- Before

![grabit mentor before](https://github.com/anmode/grabtern-frontend/assets/84488726/3187b110-cbb3-48f7-8b73-84819741b391)
- After

![grabit -mentor after](https://github.com/anmode/grabtern-frontend/assets/84488726/322e5f81-d795-4aa1-a4fb-75c29d17cbb7)

##### 2. Provide a fixed content to all the cards.
Why don't we provide just one or two data in **'Intern at'** and **'Current Status'** instead of showing all the roles.
As each mentor has there own page so providing all their data on the card itself I don't think is necessary.

Please tell me what's your view on this. So that I can start working.

**Comment by anmode** [comment]
hey @ritik48 sorry for late response.. Oh ok I like the 2nd approach. We can slice showing the extra info. so all card looks same.

**Comment by anmode** [comment]
@dhrumishah ? wanna continue
